fix

diff --git a/.github/workflows/main-labeling.yml b/.github/workflows/main-labeling.yml
--- a/.github/workflows/main-labeling.yml
+++ b/.github/workflows/main-labeling.yml
@@ -1,13 +1,65 @@
-name: labeling
+name: main-labeling
 
 on:
-  workflow_call:
+  pull_request:
+    branches:
+      - main
+    types: [ opened, edited ]
 
 permissions:
   contents: write
   pull-requests: write
 
+concurrency:
+  group: ${{ github.head_ref || github.ref_name }}
+  cancel-in-progress: true
+
 jobs:
+  title:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '18.12.1'
+
+      - name: Determine PR Title
+        id: determine-title
+        run: |
+          echo "Getting PR details"
+          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)
+
+          if [[ "$PR_BODY" == *"- [x] Patch"* ]]; then
+            echo "title=🔖 Release:patch" >> $GITHUB_OUTPUT
+          elif [[ "$PR_BODY" == *"- [x] Minor"* ]]; then
+            echo "title=🔖 Release:minor" >> $GITHUB_OUTPUT
+          elif [[ "$PR_BODY" == *"- [x] Major"* ]]; then
+            echo "title=🔖 Release:major" >> $GITHUB_OUTPUT
+          else
+            echo "title=⚠️ Warning: Change PR Title" >> $GITHUB_OUTPUT
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Update PR Title
+        run: |
+          gh pr edit ${{ github.event.pull_request.number }} --title "${{ steps.determine-title.outputs.title }}"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check PR Title
+        id: check-title
+        run: |
+          if [[ "${{ steps.determine-title.outputs.title }}" == *"Warning"* ]]; then
+            echo "Title invalid."
+            exit 1
+           else
+            echo "Title valid."
+          fi
+
   labeler:
     runs-on: ubuntu-latest
     steps:
@@ -15,4 +67,4 @@ jobs:
         id: labeling
         uses: jimschubert/labeler-action@v2
         with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.PERSONAL }}
